### ISSUE TITLE
Magerun Question

### ISSUE THREAD

**Issue by twslade** [dockerland/dex-dockerfiles-extra#4]
Curious as to why we are pegged to a version in dockerfile? I understand we have the md5 validation on downloading the phar, but why can't we grab from https://files.magerun.net/n98-magerun2.phar which always has latest version

Just thinking that the version currently is at 1.2.2, but we are storing 1.1.16. Updating could be a pain. Thoughts?

**Comment by briceburg** [comment]
Correct. The reason we download a specific version is because of the checksumming. Package maintainers always package a version of the application they're responsible for maintaining -- and dex images are more-or-less similar to this.  We can pull from latest -- although the Docker build cache comes in-to-play. You need to change the download URL or MD5 sum to trigger a new build.

I'll add a new version and point :latest to this. Will also package the development version as :dev  and a :risky version that does what you want -- busts cache (using https://github.com/dockerland/dex/blob/master/docs/HOWTO.md#busting-cache) and always downloads the latest version.

**Comment by briceburg** [comment]
well I skipped the :risky idea in favor of only providing development variants. here's the new structure. https://github.com/dockerland/dex-dockerfiles-extra/tree/master/dex-images/magerun

please close if this resolves.

**Comment by twslade** [comment]
@briceburg the other option is running the self-update command post install which exists in both n98 versions. 

See https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/SelfUpdateCommand.php
